### ISSUE TITLE
Error when benchmarking ARM with onnxruntime

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [ToriML/DNN-bench#6]
Hi,

When benchmarking ARM whit onnx-runtime backend: `./bench_model.sh ./stsb-xlm-r-multilingual.bert.opt.onnx --repeat=100 --number=1 --warmup=10 --device=arm --onnxruntime`, I got the following error:

```
onnxruntime-arm
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error
```

Thanks in advance for any help!

Matthieu

**Comment by Talmaj** [comment]
You are trying to run arm image on amd. ARM is a special architecture and can be run only on computers with this architecture, like Raspberry PIs or smartphones. On AWS you can rent ARM instances. 
In short, you should not run onnxruntime-arm on your linux/amd64 machine.
